const papers = [
  {id:1,title:'Attention Is All You Need',author:'Vaswani et al. · 2017',tag:'人工智能',status:'reading',progress:72,color:'#3e6653',favorite:true},
  {id:2,title:'The Design of Everyday Things',author:'Donald A. Norman · 2013',tag:'人机交互',status:'reading',progress:46,color:'#b86549',favorite:false},
  {id:3,title:'Situated Learning: Legitimate Peripheral Participation',author:'Lave & Wenger · 1991',tag:'认知科学',status:'unread',progress:0,color:'#68798a',favorite:true},
  {id:4,title:'Research Design: Qualitative, Quantitative, and Mixed Methods',author:'John W. Creswell · 2018',tag:'研究方法',status:'done',progress:100,color:'#8b7456',favorite:false},
  {id:5,title:'Human–AI Interaction Guidelines',author:'Amershi et al. · 2019',tag:'人机交互',status:'unread',progress:0,color:'#586e65',favorite:false},
  {id:6,title:'How People Learn II: Learners, Contexts, and Cultures',author:'National Academies · 2018',tag:'教育技术',status:'done',progress:100,color:'#76687e',favorite:true}
];

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const labels={reading:'在读',unread:'待读',done:'已完成'};
function renderContinue(){ $('#continueGrid').innerHTML=papers.filter(p=>p.status==='reading').map(p=>`<article class="continue-card"><div class="paper-cover" style="background:${p.color}"><small>${p.tag.toUpperCase()}</small><span>${p.title}</span></div><div class="continue-info"><span class="category">${p.tag}</span><h3>${p.title}</h3><p>${p.author}</p><div class="reading-progress"><div class="progress"><i style="width:${p.progress}%"></i></div><small>${p.progress}%</small></div><button onclick="advance(${p.id})">继续阅读 →</button></div></article>`).join('') }
function rows(filter='all'){return papers.filter(p=>filter==='all'||p.status===filter).map(p=>`<article class="paper-row"><div class="paper-icon">文</div><div><h3>${p.title}</h3><p>${p.author} · ${p.tag}</p></div><span class="status ${p.status}">${labels[p.status]}</span></article>`).join('')||'<div style="padding:35px;text-align:center;color:var(--muted)">没有符合条件的文献</div>'}
function renderLibrary(filter='all',query=''){let data=papers.filter(p=>(filter==='all'||(filter==='favorite'?p.favorite:p.status===filter))&&(p.title+p.author+p.tag).toLowerCase().includes(query.toLowerCase()));$('#paperCount').textContent=`共 ${data.length} 篇`;$('#libraryGrid').innerHTML=data.map(p=>`<article class="library-card"><button class="favorite ${p.favorite?'active':''}" onclick="toggleFavorite(${p.id})">${p.favorite?'♥':'♡'}</button><div class="paper-icon" style="background:${p.color}20;color:${p.color}">文</div><span class="category">${p.tag}</span><h3>${p.title}</h3><p>${p.author}</p><footer><span class="status ${p.status}">${labels[p.status]}</span><small>${p.progress}%</small></footer></article>`).join('')}
function renderRows(filter='all'){ $('#paperList').innerHTML=rows(filter) }
function toggleFavorite(id){let p=papers.find(x=>x.id===id);p.favorite=!p.favorite;renderLibrary(currentLibrary,$('#globalSearch').value);toast(p.favorite?'已收藏':'已取消收藏')}
function advance(id){let p=papers.find(x=>x.id===id);p.progress=Math.min(100,p.progress+4);if(p.progress===100)p.status='done';renderContinue();renderRows();toast(`阅读进度已更新至 ${p.progress}%`)}
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function openCnki(query){const keyword=(query||$('#globalSearch').value).trim();if(!keyword){$('#globalSearch').focus();return toast('请先输入知网检索关键词')}const url=`https://kns.cnki.net/kns8s/defaultresult/index?crossids=YSTT4HG0%2CLSTPFHG2%2CIPFD9Y60&korder=SU&kw=${encodeURIComponent(keyword)}`;window.open(url,'_blank','noopener,noreferrer')}
renderContinue();renderRows();renderLibrary();

$$('.nav-link').forEach(a=>a.onclick=()=>{let id=a.dataset.page;$$('.nav-link').forEach(x=>x.classList.toggle('active',x===a));$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$('#sidebar').classList.remove('open');window.scrollTo(0,0)});
$('.view-all').onclick=e=>{$('.nav-link[data-page="library"]').click()};
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRows(b.dataset.filter)});
let currentLibrary='all';$$('[data-library]').forEach(b=>b.onclick=()=>{$$('[data-library]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentLibrary=b.dataset.library;renderLibrary(currentLibrary,$('#globalSearch').value)});
$('#globalSearch').oninput=e=>renderLibrary(currentLibrary,e.target.value);
$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();$('.nav-link[data-page="library"]').click()}});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#globalSearch').focus()}if(e.key==='Escape')$('#addModal').classList.remove('open')});
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');
$('#cnkiBtn').onclick=()=>openCnki();$('#cnkiAdvanced').onclick=()=>window.open('https://kns.cnki.net/kns8s/AdvSearch','_blank','noopener,noreferrer');
$('#addBtn').onclick=()=>$('#addModal').classList.add('open');$('#closeModal').onclick=()=>$('#addModal').classList.remove('open');$('#addModal').onclick=e=>{if(e.target.id==='addModal')e.currentTarget.classList.remove('open')};
$('#confirmAdd').onclick=()=>{let title=$('#newTitle').value.trim();if(!title)return toast('请填写文献标题');papers.unshift({id:Date.now(),title,author:$('#newAuthor').value.trim()||'未知作者',tag:$('#newTag').value,status:'unread',progress:0,color:'#496b5a',favorite:false});renderRows();renderLibrary();$('#addModal').classList.remove('open');$('#newTitle').value='';$('#newAuthor').value='';toast('文献已添加')};
$('#saveNote').onclick=()=>{localStorage.setItem('zhiye-note',JSON.stringify({title:$('#noteTitle').value,body:$('#noteBody').value}));$('#saveStatus').textContent='刚刚保存';toast('笔记已保存到本地')};
try{let n=JSON.parse(localStorage.getItem('zhiye-note'));if(n){$('#noteTitle').value=n.title;$('#noteBody').value=n.body}}catch(e){}
let seconds=1500,timerId=null;$('#focusBtn').onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;$('#focusBtn').textContent='继续专注'}else{timerId=setInterval(()=>{if(seconds<=0){clearInterval(timerId);timerId=null;toast('完成一次专注阅读！');seconds=1500}else seconds--;$('#timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},1000);$('#focusBtn').textContent='暂停'}};
const days=['一','二','三','四','五','六','日'],values=[32,45,28,54,45,0,0];$('#chart').innerHTML=values.map((v,i)=>`<div class="bar-wrap"><div class="bar" data-value="${v}" style="height:${v?Math.max(v/60*90,8):2}%"></div><span>周${days[i]}</span></div>`).join('');

// Personal document library. Files stay in the visitor's browser via IndexedDB.
const documentDb=new Promise((resolve,reject)=>{const request=indexedDB.open('zhiye-library',1);request.onupgradeneeded=()=>request.result.createObjectStore('documents',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const safeText=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const fileKind=name=>{const ext=(name.split('.').pop()||'').toLowerCase();if(ext==='pdf')return 'PDF';if(ext==='docx')return 'WORD';if(ext==='doc')return 'WORD（旧格式）';if(['txt','md','rtf'].includes(ext))return ext.toUpperCase();return 'DOCUMENT'};
async function documentStore(mode,value){const db=await documentDb;return new Promise((resolve,reject)=>{const tx=db.transaction('documents',mode);const store=tx.objectStore('documents');const req=store[value.method](...(value.args||[]));req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function getDocuments(){return (await documentStore('readonly',{method:'getAll'})).filter(item=>item.id!=='__storage_directory__')}
async function putDocument(doc){return documentStore('readwrite',{method:'put',args:[doc]})}
async function removeDocument(id){return documentStore('readwrite',{method:'delete',args:[id]})}
function readableSize(bytes){if(!bytes)return '';const units=['B','KB','MB','GB'];const level=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3);return `${(bytes/1024**level).toFixed(level?1:0)} ${units[level]}`}
async function renderUploaded(){const docs=(await getDocuments()).sort((a,b)=>b.createdAt-a.createdAt);$('#uploadedGrid').innerHTML=docs.length?docs.map(doc=>`<article class="library-card document-card" onclick="openUploaded('${doc.id}')"><div class="paper-icon" style="background:#365f4a20;color:#365f4a">${doc.source==='url'?'↗':'文'}</div><span class="category">${safeText(doc.type)}</span><h3>${safeText(doc.title)}</h3><p>${safeText(doc.author||'未填写作者')} ${doc.size?'· '+readableSize(doc.size):''}</p><footer><span class="status unread">${doc.source==='url'?'网页文献':'本地文件'}</span><div class="doc-actions"><button class="delete-doc" onclick="event.stopPropagation();deleteUploaded('${doc.id}')">删除</button><button>阅读 →</button></div></footer></article>`).join(''):'<div class="empty-library">还没有上传文献。把 PDF 或 Word 文件拖到上方即可开始。</div>'}
async function addFiles(files){for(const file of files){await putDocument({id:`doc-${Date.now()}-${crypto.randomUUID?.()||Math.random()}`,source:'file',title:file.name.replace(/\.[^.]+$/,''),author:'',tag:'其他',type:fileKind(file.name),fileName:file.name,mime:file.type,size:file.size,blob:file,createdAt:Date.now()})}await renderUploaded();toast(`已保存 ${files.length} 个文件到本地文献库`)}
const tagGroups={
  '计算机与工程':['人工智能','计算机科学','数据科学','软件工程','网络与信息安全','电子与通信','机械工程','土木与建筑','能源与环境工程'],
  '自然科学':['数学','物理学','化学','天文学','地球科学','生命科学','生态与环境'],
  '医学与健康':['基础医学','临床医学','公共卫生','药学','心理与精神健康','运动与健康'],
  '社会科学':['经济与金融','管理学','社会学','法学','政治与国际关系','教育学','传播与媒体','人类学'],
  '人文与艺术':['哲学','历史','文学','语言学','艺术与设计','宗教与文化'],
  '交叉与方法':['认知科学','人机交互','研究方法','统计与计量','科学技术与社会','数字人文'],
  '书籍类型':['学术专著','教材与教辅','工具书','科普读物','传记','小说','诗歌与散文','商业与自我发展']
};
const tagSelect=$('#newTag');
const savedCustomTags=()=>{try{return JSON.parse(localStorage.getItem('zhiye-custom-tags'))||[]}catch(error){return []}};
function buildTagOptions(){const current=tagSelect.value;tagSelect.innerHTML=Object.entries(tagGroups).map(([group,tags])=>`<optgroup label="${group}">${tags.map(tag=>`<option value="${tag}">${tag}</option>`).join('')}</optgroup>`).join('')+`<optgroup label="我的标签">${savedCustomTags().map(tag=>`<option value="${safeText(tag)}">${safeText(tag)}</option>`).join('')}</optgroup><option value="__custom__">＋ 创建自定义标签…</option>`;if([...tagSelect.options].some(option=>option.value===current))tagSelect.value=current}
buildTagOptions();
tagSelect.insertAdjacentHTML('afterend','<input id="customTagInput" class="custom-tag-input" maxlength="24" placeholder="输入自定义标签名称" hidden>');
const customTagInput=$('#customTagInput');
tagSelect.addEventListener('change',()=>{customTagInput.hidden=tagSelect.value!=='__custom__';if(!customTagInput.hidden)setTimeout(()=>customTagInput.focus(),0)});
$('#confirmAdd').addEventListener('click',event=>{if(tagSelect.value!=='__custom__')return;const custom=customTagInput.value.trim();if(!custom){event.preventDefault();event.stopImmediatePropagation();return toast('请为自定义标签命名')}const tags=[...new Set([...savedCustomTags(),custom])];localStorage.setItem('zhiye-custom-tags',JSON.stringify(tags));const option=new Option(custom,custom,true,true);tagSelect.add(option,tagSelect.lastElementChild);customTagInput.hidden=true;customTagInput.value=''},true);
let sourceMode='file';
$$('[data-source]').forEach(button=>button.onclick=()=>{sourceMode=button.dataset.source;$$('[data-source]').forEach(item=>item.classList.toggle('active',item===button));$('#fileFields').hidden=sourceMode!=='file';$('#urlFields').hidden=sourceMode!=='url';$('#newTitle').value=''});
$('#documentFile').onchange=e=>{if(e.target.files[0]&&!$('#newTitle').value)$('#newTitle').value=e.target.files[0].name.replace(/\.[^.]+$/,'')};
$('#confirmAdd').onclick=async()=>{try{if(sourceMode==='file'){const file=$('#documentFile').files[0];if(!file)return toast('请先选择一个文件');await putDocument({id:`doc-${Date.now()}`,source:'file',title:$('#newTitle').value.trim()||file.name.replace(/\.[^.]+$/,''),author:$('#newAuthor').value.trim(),tag:$('#newTag').value,type:fileKind(file.name),fileName:file.name,mime:file.type,size:file.size,blob:file,createdAt:Date.now()})}else{const url=$('#documentUrl').value.trim();if(!/^https?:\/\//i.test(url))return toast('请输入完整的 http(s) 文献网址');await putDocument({id:`url-${Date.now()}`,source:'url',title:$('#newTitle').value.trim()||new URL(url).hostname,author:$('#newAuthor').value.trim(),tag:$('#newTag').value,type:'WEB',url,createdAt:Date.now()})}$('#addModal').classList.remove('open');$('#documentFile').value='';$('#documentUrl').value='';$('#newTitle').value='';$('#newAuthor').value='';await renderUploaded();$('.nav-link[data-page="library"]').click();toast('文献已保存到你的浏览器')}catch(error){console.error(error);toast('保存失败，文件可能超过浏览器存储空间')}};
$('#chooseFileBtn').onclick=()=>$('#quickFileInput').click();$('#quickFileInput').onchange=e=>addFiles([...e.target.files]);$('#addLinkBtn').onclick=()=>{$('#addModal').classList.add('open');$('[data-source="url"]').click()};
const zone=$('#uploadZone');['dragenter','dragover'].forEach(type=>zone.addEventListener(type,event=>{event.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(type=>zone.addEventListener(type,event=>{event.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',event=>addFiles([...event.dataTransfer.files]));
let readerObjectUrl='';
async function openUploaded(id){const db=await documentDb;const doc=await new Promise(resolve=>{const req=db.transaction('documents').objectStore('documents').get(id);req.onsuccess=()=>resolve(req.result)});if(!doc)return;$('#readerTitle').textContent=doc.title;$('#readerType').textContent=doc.type;$('#readerExternal').hidden=true;const content=$('#readerContent');content.innerHTML='';if(readerObjectUrl){URL.revokeObjectURL(readerObjectUrl);readerObjectUrl=''}if(doc.source==='url'){content.innerHTML=`<div class="reader-message"><h3>此文献来自外部网站</h3><p>部分网站禁止被嵌入，为保护登录状态和阅读权限，请在新窗口打开。</p><a href="${safeText(doc.url)}" target="_blank" rel="noopener noreferrer">打开原始文献 ↗</a></div>`;$('#readerExternal').hidden=false;$('#readerExternal').onclick=()=>window.open(doc.url,'_blank','noopener,noreferrer')}else if(doc.type==='PDF'){readerObjectUrl=URL.createObjectURL(doc.blob);content.innerHTML=`<iframe src="${readerObjectUrl}#view=FitH" title="${safeText(doc.title)}"></iframe>`}else if(doc.type==='WORD'&&window.mammoth){content.innerHTML='<div class="reader-message">正在解析 Word 文档…</div>';try{const result=await mammoth.convertToHtml({arrayBuffer:await doc.blob.arrayBuffer()});content.innerHTML=`<article class="word-content">${result.value}</article>`}catch(error){content.innerHTML='<div class="reader-message">Word 文档解析失败，请下载后阅读。</div>'}}else if(['TXT','MD','RTF'].includes(doc.type)){content.innerHTML=`<pre class="text-content">${safeText(await doc.blob.text())}</pre>`}else{readerObjectUrl=URL.createObjectURL(doc.blob);content.innerHTML=`<div class="reader-message"><h3>浏览器无法直接预览这种格式</h3><a href="${readerObjectUrl}" download="${safeText(doc.fileName)}">下载到本地阅读</a></div>`}$('#readerModal').classList.add('open');document.body.style.overflow='hidden'}
async function deleteUploaded(id){if(!confirm('确定从本地文献库删除这个文件吗？'))return;await removeDocument(id);await renderUploaded();toast('文献已从本地删除')}
function closeReader(){if(readerObjectUrl){URL.revokeObjectURL(readerObjectUrl);readerObjectUrl=''}$('#readerModal').classList.remove('open');$('#readerContent').innerHTML='';document.body.style.overflow=''}
$('#closeReader').onclick=closeReader;$('#readerModal').onclick=event=>{if(event.target.id==='readerModal')closeReader()};
window.openUploaded=openUploaded;window.deleteUploaded=deleteUploaded;
renderUploaded().catch(()=>toast('浏览器不支持本地文献存储'));

// Authing phone-code authentication and personal-space state.
const AUTHING_APP_ID='6a9ab9e9c4d642629f1b0c76';
const AUTHING_APP_HOST='https://zhiye-library.authing.cn';
let currentUser=null,authClient=null,phoneGuard=null,guardStarted=false;
function maskedPhone(user){const phone=user?.phone||user?.phoneNumber||user?.phone_number||'';return phone?phone.replace(/(\d{3})\d{4}(\d{4})/,'$1****$2'):'手机号用户'}
function renderAccount(user){currentUser=user||null;$('#userCard').classList.remove('loading');if(user){const name=user.nickname||user.username||maskedPhone(user);$('#userAvatar').textContent=name.charAt(0).toUpperCase();$('#userName').textContent=name;$('#userHint').textContent='进入个人空间'}updateSettingsAccount()}
async function showProfile(){const docs=await getDocuments().catch(()=>[]);$('#profileAvatar').textContent=$('#userAvatar').textContent;$('#profileName').textContent=currentUser.nickname||currentUser.username||'我的个人空间';$('#profilePhone').textContent=maskedPhone(currentUser);$('#profileDocCount').textContent=docs.length;$('#profileModal').classList.add('open')}
function showWorkspace(user){if(user)renderAccount(user);document.body.classList.remove('landing-mode','auth-checking');document.body.style.overflow='';window.scrollTo(0,0)}
function showLanding(){document.body.classList.add('landing-mode');document.body.classList.remove('auth-checking');location.hash='welcome';window.scrollTo(0,0);startLandingGuard()}
async function startLandingGuard(){if(guardStarted)return;if(!phoneGuard){$('#landingAuthFallback').hidden=false;return}guardStarted=true;try{await phoneGuard.start('#landingAuthContainer')}catch(error){console.error('Guard render failed',error);guardStarted=false;$('#landingAuthFallback').hidden=false;$('#landingAuthContainer').innerHTML='<div class="auth-loading"><strong>手机号登录加载失败</strong><small>请检查 Authing 应用配置</small></div>'}}
function openPhoneLogin(){if(currentUser)return showProfile();document.body.classList.add('landing-mode');document.body.classList.remove('auth-checking');document.querySelector('#signin').scrollIntoView({behavior:'smooth'});startLandingGuard()}
function initializeAuth(){if(!window.GuardFactory?.Guard){document.body.classList.remove('auth-checking');$('#landingAuthFallback').hidden=false;return}try{phoneGuard=new GuardFactory.Guard({appId:AUTHING_APP_ID,host:AUTHING_APP_HOST,config:{mode:'normal',lang:'zh-CN',title:'知页',loginMethods:['phone-code'],registerMethods:['phone'],target:'#landingAuthContainer',contentCss:'.g2-view-header{display:none!important}.g2-view-container{min-height:0!important;height:auto!important;padding:0!important}'}});const enter=user=>{showWorkspace(user);toast('欢迎回来，阅读空间已开启')};phoneGuard.on('login',enter);phoneGuard.on('register',enter);phoneGuard.on('login-error',error=>{const code=String(error?.code||error?.apiCode||'');toast(code==='1576'?'当前账号尚未获得知页访问权限':'登录未完成，请检查验证码')});phoneGuard.on('load-error',()=>{$('#landingAuthFallback').hidden=false});phoneGuard.getAuthClient().then(client=>{authClient=client;return client.getCurrentUser()}).then(user=>{if(user)showWorkspace(user);else showLanding()}).catch(error=>{console.warn('Auth status check failed',error);showLanding()})}catch(error){console.error(error);phoneGuard=null;showLanding()}}
$('#landingLoginBtn').onclick=openPhoneLogin;$('#startReadingBtn').onclick=openPhoneLogin;$('#userCard').onclick=()=>currentUser&&showProfile();
$('#closeProfile').onclick=()=>$('#profileModal').classList.remove('open');$('#profileModal').onclick=event=>{if(event.target.id==='profileModal')event.currentTarget.classList.remove('open')};
$('#logoutBtn').onclick=async()=>{const logoutButton=$('#logoutBtn');try{logoutButton.disabled=true;logoutButton.textContent='正在退出…';if(authClient)await authClient.logout();currentUser=null;$('#profileModal').classList.remove('open');showLanding();toast('已安全退出')}catch(error){toast('退出失败，请稍后重试')}finally{logoutButton.disabled=false;logoutButton.textContent='退出登录'}};
initializeAuth();

// Settings: storage, appearance and account overview.
document.querySelector('.profile-info>div:nth-child(2)')?.remove();
$('.profile-info').style.gridTemplateColumns='1fr';
function updateSettingsAccount(){const avatar=$('#settingsAvatar');if(!avatar)return;avatar.textContent=currentUser?$('#userAvatar').textContent:'游';$('#settingsUserName').textContent=currentUser?($('#userName').textContent||'手机号用户'):'游客预览';$('#settingsUserStatus').textContent=currentUser?`${maskedPhone(currentUser)} · 已登录`:'登录后可使用个人空间';$('#settingsLoginBtn').textContent=currentUser?'个人空间':'登录'}
$('#settingsLoginBtn')?.closest('.settings-card')?.remove();
async function updateStorageSettings(){const docs=await getDocuments().catch(()=>[]);$('#settingsDocCount').textContent=docs.length;const ownBytes=docs.reduce((total,doc)=>total+(doc.size||0),0);if(currentStorageMode()==='folder'){$('#storageUsage').textContent=readableSize(ownBytes)||'0 B';$('#storageDetail').textContent='自定义文件夹容量由磁盘剩余空间决定，不受浏览器配额限制';$('#storageBar').style.width='0%';return}let usage=ownBytes,quota=0;try{if(navigator.storage?.estimate){const estimate=await navigator.storage.estimate();usage=estimate.usage||ownBytes;quota=estimate.quota||0}}catch(error){}$('#storageUsage').textContent=readableSize(usage)||'0 B';$('#storageDetail').textContent=quota?`浏览器为此来源提供约 ${readableSize(quota)} 可用空间`:`已保存文件约 ${readableSize(ownBytes)||'0 B'}`;$('#storageBar').style.width=quota?`${Math.min(100,usage/quota*100)}%`:'0%'}
$('.nav-link[data-page="settings"]').addEventListener('click',()=>{updateStorageSettings();updateSettingsAccount()});
$('#clearLibraryBtn').onclick=async()=>{const docs=await getDocuments().catch(()=>[]);if(!docs.length)return toast('本地文献库已经是空的');if(!confirm(`确定删除当前浏览器中的 ${docs.length} 篇文献吗？此操作无法撤销。`))return;await documentStore('readwrite',{method:'clear'});await renderUploaded();await updateStorageSettings();toast('本地文献数据已清除')};
const darkToggle=$('#darkModeToggle'),rememberTheme=$('#rememberTheme');
function applyTheme(dark,save=true){document.body.classList.toggle('dark',dark);darkToggle.checked=dark;if(save&&rememberTheme.checked)localStorage.setItem('zhiye-theme',dark?'dark':'light')}
const savedTheme=localStorage.getItem('zhiye-theme');if(savedTheme)applyTheme(savedTheme==='dark',false);else darkToggle.checked=document.body.classList.contains('dark');
$('#themeBtn').onclick=()=>applyTheme(!document.body.classList.contains('dark'));darkToggle.onchange=()=>applyTheme(darkToggle.checked);rememberTheme.onchange=()=>{if(rememberTheme.checked)localStorage.setItem('zhiye-theme',document.body.classList.contains('dark')?'dark':'light');else localStorage.removeItem('zhiye-theme')};
updateStorageSettings();updateSettingsAccount();

// User-selected storage. File System Access is available on Chromium-based browsers.
let customDirectoryHandle=null;
const storageLocation=$('.storage-location');
storageLocation.querySelector('strong').id='storageLocationName';
storageLocation.insertAdjacentHTML('afterend','<div class="storage-choice"><small>选择新上传文献的存储方式</small><div class="storage-options"><button class="storage-option" id="browserStorageOption"><strong>浏览器存储</strong><span>无需授权，适合当前设备阅读</span></button><button class="storage-option" id="folderStorageOption"><strong>自定义文件夹</strong><span>同时保存副本到你指定的目录</span></button></div><div class="folder-row" id="folderRow" hidden><code id="folderName">尚未选择文件夹</code><button id="chooseFolderBtn">选择文件夹</button></div></div>');
function currentStorageMode(){return localStorage.getItem('zhiye-storage-mode')||'browser'}
function renderStorageChoice(){const custom=currentStorageMode()==='folder';$('#browserStorageOption').classList.toggle('active',!custom);$('#folderStorageOption').classList.toggle('active',custom);$('#folderRow').hidden=!custom;$('#storageLocationName').textContent=custom?(customDirectoryHandle?`自定义文件夹 · ${customDirectoryHandle.name}`:'自定义文件夹 · 等待授权'):'此浏览器 · IndexedDB';$('.storage-badge').textContent=custom?'自定义存储':'本地存储'}
async function restoreStorageDirectory(){try{const record=await documentStore('readonly',{method:'get',args:['__storage_directory__']});if(record?.handle){customDirectoryHandle=record.handle;$('#folderName').textContent=record.handle.name}}catch(error){}renderStorageChoice()}
async function chooseStorageDirectory(){if(!window.showDirectoryPicker){toast('当前浏览器不支持选择文件夹，请使用最新版 Chrome 或 Edge');localStorage.setItem('zhiye-storage-mode','browser');return renderStorageChoice()}try{const handle=await window.showDirectoryPicker({mode:'readwrite',id:'zhiye-documents'});const permission=await handle.requestPermission({mode:'readwrite'});if(permission!=='granted')return toast('未获得文件夹写入权限');customDirectoryHandle=handle;await putDocument({id:'__storage_directory__',handle,createdAt:0});localStorage.setItem('zhiye-storage-mode','folder');$('#folderName').textContent=handle.name;renderStorageChoice();toast(`已选择文件夹：${handle.name}`)}catch(error){if(error.name!=='AbortError')toast('无法使用该文件夹，请重新授权')}}
async function copyToCustomFolder(file){if(currentStorageMode()!=='folder'||!customDirectoryHandle)return null;try{let permission=await customDirectoryHandle.queryPermission({mode:'readwrite'});if(permission!=='granted')permission=await customDirectoryHandle.requestPermission({mode:'readwrite'});if(permission!=='granted')throw new Error('permission denied');const handle=await customDirectoryHandle.getFileHandle(file.name,{create:true});const writable=await handle.createWritable();await writable.write(file);await writable.close();return handle}catch(error){toast('自定义文件夹写入失败，文件将改存到浏览器中');return null}}
$('#browserStorageOption').onclick=async()=>{localStorage.setItem('zhiye-storage-mode','browser');if(navigator.storage?.persist)await navigator.storage.persist().catch(()=>false);renderStorageChoice();updateStorageSettings();toast('新文献将持久保存在浏览器中')};
$('#folderStorageOption').onclick=()=>{localStorage.setItem('zhiye-storage-mode','folder');renderStorageChoice();if(!customDirectoryHandle)chooseStorageDirectory()};$('#chooseFolderBtn').onclick=chooseStorageDirectory;
async function addFiles(files){for(const file of files){const fileHandle=await copyToCustomFolder(file);const record={id:`doc-${Date.now()}-${crypto.randomUUID?.()||Math.random()}`,source:'file',title:file.name.replace(/\.[^.]+$/,''),author:'',tag:'其他',type:fileKind(file.name),fileName:file.name,mime:file.type,size:file.size,createdAt:Date.now()};if(fileHandle)record.fileHandle=fileHandle;else record.blob=file;await putDocument(record)}await renderUploaded();updateStorageSettings();toast(`已保存 ${files.length} 个文件${currentStorageMode()==='folder'?'到自定义文件夹':'到本地文献库'}`)}
$('#clearLibraryBtn').onclick=async()=>{const docs=await getDocuments().catch(()=>[]);if(!docs.length)return toast('本地文献库已经是空的');if(!confirm(`确定删除网站中的 ${docs.length} 篇文献记录吗？自定义文件夹里的文件副本会保留。`))return;for(const doc of docs)await removeDocument(doc.id);await renderUploaded();await updateStorageSettings();toast('本地文献记录已清除')};
restoreStorageDirectory();

$('#confirmAdd').onclick=async()=>{try{if(sourceMode==='file'){const file=$('#documentFile').files[0];if(!file)return toast('请先选择一个文件');const fileHandle=await copyToCustomFolder(file);const record={id:`doc-${Date.now()}`,source:'file',title:$('#newTitle').value.trim()||file.name.replace(/\.[^.]+$/,''),author:$('#newAuthor').value.trim(),tag:$('#newTag').value,type:fileKind(file.name),fileName:file.name,mime:file.type,size:file.size,createdAt:Date.now()};if(fileHandle)record.fileHandle=fileHandle;else record.blob=file;await putDocument(record)}else{const url=$('#documentUrl').value.trim();if(!/^https?:\/\//i.test(url))return toast('请输入完整的 http(s) 文献网址');await putDocument({id:`url-${Date.now()}`,source:'url',title:$('#newTitle').value.trim()||new URL(url).hostname,author:$('#newAuthor').value.trim(),tag:$('#newTag').value,type:'WEB',url,createdAt:Date.now()})}$('#addModal').classList.remove('open');$('#documentFile').value='';$('#documentUrl').value='';$('#newTitle').value='';$('#newAuthor').value='';await renderUploaded();await updateStorageSettings();$('.nav-link[data-page="library"]').click();toast('文献已保存')}catch(error){console.error(error);toast('保存失败，请检查存储权限或可用空间')}};
window.openUploaded=async id=>{const db=await documentDb;const doc=await new Promise(resolve=>{const req=db.transaction('documents').objectStore('documents').get(id);req.onsuccess=()=>resolve(req.result)});if(!doc)return;let blob=doc.blob;if(!blob&&doc.fileHandle){try{let permission=await doc.fileHandle.queryPermission({mode:'read'});if(permission!=='granted')permission=await doc.fileHandle.requestPermission({mode:'read'});if(permission==='granted')blob=await doc.fileHandle.getFile()}catch(error){}}$('#readerTitle').textContent=doc.title;$('#readerType').textContent=doc.type;$('#readerExternal').hidden=true;const content=$('#readerContent');content.innerHTML='';if(readerObjectUrl){URL.revokeObjectURL(readerObjectUrl);readerObjectUrl=''}if(doc.source==='url'){content.innerHTML=`<div class="reader-message"><h3>此文献来自外部网站</h3><a href="${safeText(doc.url)}" target="_blank" rel="noopener noreferrer">打开原始文献 ↗</a></div>`;$('#readerExternal').hidden=false;$('#readerExternal').onclick=()=>window.open(doc.url,'_blank','noopener,noreferrer')}else if(!blob){content.innerHTML='<div class="reader-message"><h3>需要重新授权文件夹</h3><p>请前往设置重新选择原存储文件夹。</p></div>'}else if(doc.type==='PDF'){readerObjectUrl=URL.createObjectURL(blob);content.innerHTML=`<iframe src="${readerObjectUrl}#view=FitH" title="${safeText(doc.title)}"></iframe>`}else if(doc.type==='WORD'&&window.mammoth){content.innerHTML='<div class="reader-message">正在解析 Word 文档…</div>';try{const result=await mammoth.convertToHtml({arrayBuffer:await blob.arrayBuffer()});content.innerHTML=`<article class="word-content">${result.value}</article>`}catch(error){content.innerHTML='<div class="reader-message">Word 文档解析失败，请下载后阅读。</div>'}}else if(['TXT','MD','RTF'].includes(doc.type)){content.innerHTML=`<pre class="text-content">${safeText(await blob.text())}</pre>`}else{readerObjectUrl=URL.createObjectURL(blob);content.innerHTML=`<div class="reader-message"><a href="${readerObjectUrl}" download="${safeText(doc.fileName)}">下载到本地阅读</a></div>`}$('#readerModal').classList.add('open');document.body.style.overflow='hidden'};
