const papers = [
  {id:1,title:'Attention Is All You Need',author:'Vaswani et al. · 2017',tag:'人工智能',status:'reading',progress:72,color:'#3e6653',favorite:true},
  {id:2,title:'The Design of Everyday Things',author:'Donald A. Norman · 2013',tag:'人机交互',status:'reading',progress:46,color:'#b86549',favorite:false},
  {id:3,title:'Situated Learning: Legitimate Peripheral Participation',author:'Lave & Wenger · 1991',tag:'认知科学',status:'unread',progress:0,color:'#68798a',favorite:true},
  {id:4,title:'Research Design: Qualitative, Quantitative, and Mixed Methods',author:'John W. Creswell · 2018',tag:'研究方法',status:'done',progress:100,color:'#8b7456',favorite:false},
  {id:5,title:'Human–AI Interaction Guidelines',author:'Amershi et al. · 2019',tag:'人机交互',status:'unread',progress:0,color:'#586e65',favorite:false},
  {id:6,title:'How People Learn II: Learners, Contexts, and Cultures',author:'National Academies · 2018',tag:'教育技术',status:'done',progress:100,color:'#76687e',favorite:true}
];

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const labels={reading:'在读',unread:'待读',done:'已完成'};
function renderContinue(){ $('#continueGrid').innerHTML=papers.filter(p=>p.status==='reading').map(p=>`<article class="continue-card"><div class="paper-cover" style="background:${p.color}"><small>${p.tag.toUpperCase()}</small><span>${p.title}</span></div><div class="continue-info"><span class="category">${p.tag}</span><h3>${p.title}</h3><p>${p.author}</p><div class="reading-progress"><div class="progress"><i style="width:${p.progress}%"></i></div><small>${p.progress}%</small></div><button onclick="advance(${p.id})">继续阅读 →</button></div></article>`).join('') }
function rows(filter='all'){return papers.filter(p=>filter==='all'||p.status===filter).map(p=>`<article class="paper-row"><div class="paper-icon">文</div><div><h3>${p.title}</h3><p>${p.author} · ${p.tag}</p></div><span class="status ${p.status}">${labels[p.status]}</span></article>`).join('')||'<div style="padding:35px;text-align:center;color:var(--muted)">没有符合条件的文献</div>'}
function renderLibrary(filter='all',query=''){let data=papers.filter(p=>(filter==='all'||(filter==='favorite'?p.favorite:p.status===filter))&&(p.title+p.author+p.tag).toLowerCase().includes(query.toLowerCase()));$('#paperCount').textContent=`共 ${data.length} 篇`;$('#libraryGrid').innerHTML=data.map(p=>`<article class="library-card"><button class="favorite ${p.favorite?'active':''}" onclick="toggleFavorite(${p.id})">${p.favorite?'♥':'♡'}</button><div class="paper-icon" style="background:${p.color}20;color:${p.color}">文</div><span class="category">${p.tag}</span><h3>${p.title}</h3><p>${p.author}</p><footer><span class="status ${p.status}">${labels[p.status]}</span><small>${p.progress}%</small></footer></article>`).join('')}
function renderRows(filter='all'){ $('#paperList').innerHTML=rows(filter) }
function toggleFavorite(id){let p=papers.find(x=>x.id===id);p.favorite=!p.favorite;renderLibrary(currentLibrary,$('#globalSearch').value);toast(p.favorite?'已收藏':'已取消收藏')}
function advance(id){let p=papers.find(x=>x.id===id);p.progress=Math.min(100,p.progress+4);if(p.progress===100)p.status='done';renderContinue();renderRows();toast(`阅读进度已更新至 ${p.progress}%`)}
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function openCnki(query){const keyword=(query||$('#globalSearch').value).trim();if(!keyword){$('#globalSearch').focus();return toast('请先输入知网检索关键词')}const url=`https://kns.cnki.net/kns8s/defaultresult/index?crossids=YSTT4HG0%2CLSTPFHG2%2CIPFD9Y60&korder=SU&kw=${encodeURIComponent(keyword)}`;window.open(url,'_blank','noopener,noreferrer')}
renderContinue();renderRows();renderLibrary();

$$('.nav-link').forEach(a=>a.onclick=()=>{let id=a.dataset.page;$$('.nav-link').forEach(x=>x.classList.toggle('active',x===a));$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$('#sidebar').classList.remove('open');window.scrollTo(0,0)});
$('.view-all').onclick=e=>{$('.nav-link[data-page="library"]').click()};
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRows(b.dataset.filter)});
let currentLibrary='all';$$('[data-library]').forEach(b=>b.onclick=()=>{$$('[data-library]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentLibrary=b.dataset.library;renderLibrary(currentLibrary,$('#globalSearch').value)});
$('#globalSearch').oninput=e=>renderLibrary(currentLibrary,e.target.value);
$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();$('.nav-link[data-page="library"]').click()}});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#globalSearch').focus()}if(e.key==='Escape')$('#addModal').classList.remove('open')});
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');
$('#cnkiBtn').onclick=()=>openCnki();$('#cnkiAdvanced').onclick=()=>window.open('https://kns.cnki.net/kns8s/AdvSearch','_blank','noopener,noreferrer');
$('#addBtn').onclick=()=>$('#addModal').classList.add('open');$('#closeModal').onclick=()=>$('#addModal').classList.remove('open');$('#addModal').onclick=e=>{if(e.target.id==='addModal')e.currentTarget.classList.remove('open')};
$('#confirmAdd').onclick=()=>{let title=$('#newTitle').value.trim();if(!title)return toast('请填写文献标题');papers.unshift({id:Date.now(),title,author:$('#newAuthor').value.trim()||'未知作者',tag:$('#newTag').value,status:'unread',progress:0,color:'#496b5a',favorite:false});renderRows();renderLibrary();$('#addModal').classList.remove('open');$('#newTitle').value='';$('#newAuthor').value='';toast('文献已添加')};
$('#saveNote').onclick=()=>{localStorage.setItem('zhiye-note',JSON.stringify({title:$('#noteTitle').value,body:$('#noteBody').value}));$('#saveStatus').textContent='刚刚保存';toast('笔记已保存到本地')};
try{let n=JSON.parse(localStorage.getItem('zhiye-note'));if(n){$('#noteTitle').value=n.title;$('#noteBody').value=n.body}}catch(e){}
let seconds=1500,timerId=null;$('#focusBtn').onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;$('#focusBtn').textContent='继续专注'}else{timerId=setInterval(()=>{if(seconds<=0){clearInterval(timerId);timerId=null;toast('完成一次专注阅读！');seconds=1500}else seconds--;$('#timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},1000);$('#focusBtn').textContent='暂停'}};
const days=['一','二','三','四','五','六','日'],values=[32,45,28,54,45,0,0];$('#chart').innerHTML=values.map((v,i)=>`<div class="bar-wrap"><div class="bar" data-value="${v}" style="height:${v?Math.max(v/60*90,8):2}%"></div><span>周${days[i]}</span></div>`).join('');

// Personal document library. Files stay in the visitor's browser via IndexedDB.
const documentDb=new Promise((resolve,reject)=>{const request=indexedDB.open('zhiye-library',1);request.onupgradeneeded=()=>request.result.createObjectStore('documents',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const safeText=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const fileKind=name=>{const ext=(name.split('.').pop()||'').toLowerCase();if(ext==='pdf')return 'PDF';if(ext==='docx')return 'WORD';if(ext==='doc')return 'WORD（旧格式）';if(['txt','md','rtf'].includes(ext))return ext.toUpperCase();return 'DOCUMENT'};
async function documentStore(mode,value){const db=await documentDb;return new Promise((resolve,reject)=>{const tx=db.transaction('documents',mode);const store=tx.objectStore('documents');const req=store[value.method](...(value.args||[]));req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function getDocuments(){return documentStore('readonly',{method:'getAll'})}
async function putDocument(doc){return documentStore('readwrite',{method:'put',args:[doc]})}
async function removeDocument(id){return documentStore('readwrite',{method:'delete',args:[id]})}
function readableSize(bytes){if(!bytes)return '';const units=['B','KB','MB','GB'];const level=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3);return `${(bytes/1024**level).toFixed(level?1:0)} ${units[level]}`}
async function renderUploaded(){const docs=(await getDocuments()).sort((a,b)=>b.createdAt-a.createdAt);$('#uploadedGrid').innerHTML=docs.length?docs.map(doc=>`<article class="library-card document-card" onclick="openUploaded('${doc.id}')"><div class="paper-icon" style="background:#365f4a20;color:#365f4a">${doc.source==='url'?'↗':'文'}</div><span class="category">${safeText(doc.type)}</span><h3>${safeText(doc.title)}</h3><p>${safeText(doc.author||'未填写作者')} ${doc.size?'· '+readableSize(doc.size):''}</p><footer><span class="status unread">${doc.source==='url'?'网页文献':'本地文件'}</span><div class="doc-actions"><button class="delete-doc" onclick="event.stopPropagation();deleteUploaded('${doc.id}')">删除</button><button>阅读 →</button></div></footer></article>`).join(''):'<div class="empty-library">还没有上传文献。把 PDF 或 Word 文件拖到上方即可开始。</div>'}
async function addFiles(files){for(const file of files){await putDocument({id:`doc-${Date.now()}-${crypto.randomUUID?.()||Math.random()}`,source:'file',title:file.name.replace(/\.[^.]+$/,''),author:'',tag:'其他',type:fileKind(file.name),fileName:file.name,mime:file.type,size:file.size,blob:file,createdAt:Date.now()})}await renderUploaded();toast(`已保存 ${files.length} 个文件到本地文献库`)}
let sourceMode='file';
$$('[data-source]').forEach(button=>button.onclick=()=>{sourceMode=button.dataset.source;$$('[data-source]').forEach(item=>item.classList.toggle('active',item===button));$('#fileFields').hidden=sourceMode!=='file';$('#urlFields').hidden=sourceMode!=='url';$('#newTitle').value=''});
$('#documentFile').onchange=e=>{if(e.target.files[0]&&!$('#newTitle').value)$('#newTitle').value=e.target.files[0].name.replace(/\.[^.]+$/,'')};
$('#confirmAdd').onclick=async()=>{try{if(sourceMode==='file'){const file=$('#documentFile').files[0];if(!file)return toast('请先选择一个文件');await putDocument({id:`doc-${Date.now()}`,source:'file',title:$('#newTitle').value.trim()||file.name.replace(/\.[^.]+$/,''),author:$('#newAuthor').value.trim(),tag:$('#newTag').value,type:fileKind(file.name),fileName:file.name,mime:file.type,size:file.size,blob:file,createdAt:Date.now()})}else{const url=$('#documentUrl').value.trim();if(!/^https?:\/\//i.test(url))return toast('请输入完整的 http(s) 文献网址');await putDocument({id:`url-${Date.now()}`,source:'url',title:$('#newTitle').value.trim()||new URL(url).hostname,author:$('#newAuthor').value.trim(),tag:$('#newTag').value,type:'WEB',url,createdAt:Date.now()})}$('#addModal').classList.remove('open');$('#documentFile').value='';$('#documentUrl').value='';$('#newTitle').value='';$('#newAuthor').value='';await renderUploaded();$('.nav-link[data-page="library"]').click();toast('文献已保存到你的浏览器')}catch(error){console.error(error);toast('保存失败，文件可能超过浏览器存储空间')}};
$('#chooseFileBtn').onclick=()=>$('#quickFileInput').click();$('#quickFileInput').onchange=e=>addFiles([...e.target.files]);$('#addLinkBtn').onclick=()=>{$('#addModal').classList.add('open');$('[data-source="url"]').click()};
const zone=$('#uploadZone');['dragenter','dragover'].forEach(type=>zone.addEventListener(type,event=>{event.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(type=>zone.addEventListener(type,event=>{event.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',event=>addFiles([...event.dataTransfer.files]));
let readerObjectUrl='';
async function openUploaded(id){const db=await documentDb;const doc=await new Promise(resolve=>{const req=db.transaction('documents').objectStore('documents').get(id);req.onsuccess=()=>resolve(req.result)});if(!doc)return;$('#readerTitle').textContent=doc.title;$('#readerType').textContent=doc.type;$('#readerExternal').hidden=true;const content=$('#readerContent');content.innerHTML='';if(readerObjectUrl){URL.revokeObjectURL(readerObjectUrl);readerObjectUrl=''}if(doc.source==='url'){content.innerHTML=`<div class="reader-message"><h3>此文献来自外部网站</h3><p>部分网站禁止被嵌入，为保护登录状态和阅读权限，请在新窗口打开。</p><a href="${safeText(doc.url)}" target="_blank" rel="noopener noreferrer">打开原始文献 ↗</a></div>`;$('#readerExternal').hidden=false;$('#readerExternal').onclick=()=>window.open(doc.url,'_blank','noopener,noreferrer')}else if(doc.type==='PDF'){readerObjectUrl=URL.createObjectURL(doc.blob);content.innerHTML=`<iframe src="${readerObjectUrl}#view=FitH" title="${safeText(doc.title)}"></iframe>`}else if(doc.type==='WORD'&&window.mammoth){content.innerHTML='<div class="reader-message">正在解析 Word 文档…</div>';try{const result=await mammoth.convertToHtml({arrayBuffer:await doc.blob.arrayBuffer()});content.innerHTML=`<article class="word-content">${result.value}</article>`}catch(error){content.innerHTML='<div class="reader-message">Word 文档解析失败，请下载后阅读。</div>'}}else if(['TXT','MD','RTF'].includes(doc.type)){content.innerHTML=`<pre class="text-content">${safeText(await doc.blob.text())}</pre>`}else{readerObjectUrl=URL.createObjectURL(doc.blob);content.innerHTML=`<div class="reader-message"><h3>浏览器无法直接预览这种格式</h3><a href="${readerObjectUrl}" download="${safeText(doc.fileName)}">下载到本地阅读</a></div>`}$('#readerModal').classList.add('open');document.body.style.overflow='hidden'}
async function deleteUploaded(id){if(!confirm('确定从本地文献库删除这个文件吗？'))return;await removeDocument(id);await renderUploaded();toast('文献已从本地删除')}
function closeReader(){if(readerObjectUrl){URL.revokeObjectURL(readerObjectUrl);readerObjectUrl=''}$('#readerModal').classList.remove('open');$('#readerContent').innerHTML='';document.body.style.overflow=''}
$('#closeReader').onclick=closeReader;$('#readerModal').onclick=event=>{if(event.target.id==='readerModal')closeReader()};
window.openUploaded=openUploaded;window.deleteUploaded=deleteUploaded;
renderUploaded().catch(()=>toast('浏览器不支持本地文献存储'));
